flowchart TD
    A[Inicio] -->|Acceder| B[Administrador: Administrar inventario]
    B --> C{¿Necesidad de reabastecimiento?}
    C -->|Sí| D[Administrador: Ordenar stock]
    C -->|No| E[Continuar]
    E --> F[Administrador: Crear/editar precios y promociones]
    F --> G{¿Necesidad de reporte?}
    G -->|Sí| H[Administrador: Visualizar reportes y descripciones de inventario]
    G -->|No| I[Continuar]
    I --> J[Cajero: Procesar pagos]
    J --> K{¿Forma de pago?}
    K -->|Tarjeta| L[Procesar tarjeta de crédito]
    K -->|Efectivo| M[Recibir efectivo]
    L --> N[Generar ticket]
    M --> N
    N --> O[Entregar compra]
    O --> P{¿Necesidad de buscar producto?}
    P -->|Sí| Q[Cajero: Buscar producto]
    P -->|No| R[Fin]
    Q --> S[Seleccionar producto]
    S --> R[Fin]