classDiagram
    class Usuario {
        +nombre: String
        +login()
    }
    class Cajero {
        -idCajero: Int
        +ingresarCompra()
        +calcularTotal()
        +recibirPago()
        +darCambio()
        +consultarPrecio()
        +mostrarListaProductos()
    }
    class Administrador {
        -idAdministrador: Int
        +agregarProducto()
        +verReporteVentas()
        +buscarProducto()
        +cambiarPrecio()
        +eliminarProducto()
    }
    Usuario <|-- Cajero
    Usuario <|-- Administrador
    
    class Producto {
        -idProducto: Int
        -nombre: String
        -precio: Double
        +getPrecio(): Double
        +setPrecio()
    }
    class Venta {
        -idVenta: Int
        -total: Double
        -fecha: String
        +calcularTotal()
        +getTotal(): Double
    }
    class Compra {
        -idCompra: Int
        -cantidad: Int
        -subtotal: Double
    }
    class Inventario {
        -listaProductos: List~Producto~
        +agregarProducto()
        +eliminarProducto()
        +buscarProducto()
        +actualizarPrecio()
    }
    Administrador -- Inventario : gestiona
    Cajero -- Venta : realiza
    Venta *-- Compra : contiene 1..*
    Compra o-- Producto : incluye 1
    Inventario o-- Producto : almacena 0..*
    
    class Cuenta {
        +usuario: String
        +password: String
        +autenticar()
    }
    Administrador -- Cuenta : tiene 1
```