erDiagram
    PRODUCTO {
        int id
        string nombre
        int cantidad
    }
    INVENTARIO {
        int id
        date fecha
        int cantidad
    }
    PRODUCTO }o--|| INVENTARIO : pertenece
    PAIDO {
        int id
        date fecha
        float monto
    }
    FORMA_PAGO {
        int id
        string tipo
    }
    PAIDO }o--|| FORMA_PAGO : utiliza
    EMPLEADO {
        int id
        string rol
    }
    PRODUCTO }|--|| EMPLEADO : vende
    EMPLEADO ||--o{ PAIDO : procesa
    REPORTE {
        int id
        date fecha
        string descripcion
    }
    PRODUCTO }o--|| REPORTE : objeto
    INVENTARIO }o--|| REPORTE : objeto
    CLIENTE {
        int id
        string nombre
        string telefono
    }
    PAIDO }o--|| CLIENTE : cliente
    TICKE {
        int id
        date fecha
        float monto
    }
    PAIDO }o--|| TICKE : relacionado